-- MySQL Script generated by MySQL Workbench
-- Wed 15 Jan 2020 11:00:00 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Date of birth` DATE NULL,
  `Adress` VARCHAR(45) NULL,
  `Phone number` VARCHAR(45) NULL,
  `Salary` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical` (
  `ID-doctor-overtime` VARCHAR(45) NOT NULL,
  `overtime rate` INT NULL,
  `ID` INT NULL,
  PRIMARY KEY (`ID-doctor-overtime`),
  INDEX `fk_Medical_1_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_Medical_1`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`Doctor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Specialist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specialist` (
  `ID-doctor-field` INT NOT NULL,
  `ID` INT NULL,
  `field area` VARCHAR(45) NULL,
  PRIMARY KEY (`ID-doctor-field`),
  INDEX `fk_Specialist_1_idx` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_Specialist_1`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`Doctor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`appointment` (
  `idappointment` INT NOT NULL,
  `idpatient` INT NULL,
  `appointmentdate` DATE NULL,
  `appointmenttime` VARCHAR(45) NULL,
  PRIMARY KEY (`idappointment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `idPatient` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Adress` VARCHAR(45) NULL,
  `Date of birth` VARCHAR(45) NULL,
  `Phone number` VARCHAR(45) NULL,
  `ID` INT NULL,
  `id appointment` INT NULL,
  PRIMARY KEY (`idPatient`),
  INDEX `fk_Patient_1_idx` (`ID` ASC) VISIBLE,
  INDEX `fk_Patient_2_idx` (`id appointment` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_1`
    FOREIGN KEY (`ID`)
    REFERENCES `mydb`.`Doctor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patient_2`
    FOREIGN KEY (`id appointment`)
    REFERENCES `mydb`.`appointment` (`idappointment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `idPayment` INT NOT NULL,
  `idappointment` INT NULL,
  `method` VARCHAR(45) NULL,
  `details` VARCHAR(45) NULL,
  PRIMARY KEY (`idPayment`),
  INDEX `fk_Payment_1_idx` (`idappointment` ASC) VISIBLE,
  CONSTRAINT `fk_Payment_1`
    FOREIGN KEY (`idappointment`)
    REFERENCES `mydb`.`appointment` (`idappointment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bill` (
  `idBill` INT NOT NULL,
  `total` VARCHAR(45) NULL,
  `idappointment` INT NULL,
  PRIMARY KEY (`idBill`),
  INDEX `fk_Bill_1_idx` (`idappointment` ASC) VISIBLE,
  CONSTRAINT `fk_Bill_1`
    FOREIGN KEY (`idappointment`)
    REFERENCES `mydb`.`appointment` (`idappointment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
